### ISSUE TITLE
blog.winter.dev is offline

### ISSUE THREAD

**Issue by Beeblerox** [IainWinter/winter-dev-static#1]
Hello! I've tried to read the articles linked in your youtube videos about GJK and EPA algorithms, but seems like your blog is down

**Comment by Beeblerox** [comment]
oh, i see now that articles moved to another address. maybe you should change links in the descriptions of youtube videos then?

**Comment by Beeblerox** [comment]
Anyway, thanks for the great content!

**Comment by IainWinter** [comment]
Thanks for bringing this up, I was wondering if that was gonna be an issue. I’ll put a redirect and change the links.

**Comment by IainWinter** [comment]
Ok I added a redirect for blog.winter.dev to the github.io site and fixed all the links in the descriptions of videos.
